DROP TABLE IF EXISTS POKEMONES;

CREATE TABLE POKEMONES (
  ID bigint auto_increment PRIMARY KEY,
  APODO VARCHAR2 (60 Byte) NOT NULL,
  ESPECIE VARCHAR2 (50 Byte) NOT NULL,
  ATAQUE INT NOT NULL,
  DEFENSA INT NOT NULL,
  SALUD INT NOT NULL
);



